### ISSUE TITLE
Dosen't work with cyrillic symbols in fisrt_name

### ISSUE THREAD

**Issue by Slava191** [nimaxin/init-data-py#2]
If first_name contains cyrillic symbols `validate` method always throwing errors like this:
`init_data_py.errors.errors.SignInvalidError: signature (hash) is invalid.`

**Comment by nimaxin** [comment]
Hi, thanks for reporting the issue!

Could you please provide the `init_data` that triggered the error? Could you also share the `bot_token` (*revoke it before sending*)? If you can't revoke the bot_token, that's fine. I'd just need the exact `first_name` value that caused the issue. I've tested Cyrillic and Hebrew symbols on my end, and they seem to work correctly, so having your date will help me figure out what's going wrong.

**Comment by Slava191** [comment]
Thank you for improvements! It works perfect now!
